#!/bin/bash
REPORTER_PATH="./reporter"
DNS_PATH="./dns"
LBAGENT_PATH="./lb_agent"
API_EXAMPLE_PATH="./api/cpp/example"

usage()
{
    echo ""
    echo "=======启动子系统=========="
    echo "Usage ./run [reporter|dns|lbagent|test]"
    echo

    echo "=======测试工具============"
    echo "Usage ./run test gethost ModID CmdID"
    echo "Usage ./run test getroute ModID CmdID"
    echo "Usage ./run test report ModID CmdID IP Port 0|1  --- 0:SUCC, 1:OVERLOAD"
    echo "Usage ./run test simulator ModID CmdID [errRate(0-10)] [queryCnt(0-999999)]"
    echo "Usage ./run test qps ThreadNum"
    echo "Usage ./run test example ModID CmdID"
    echo
}

if [ "$1" = "test" ]; then
    if [ "$2" = "gethost" ]; then
        $PWD/$API_EXAMPLE_PATH/get_host $3 $4 
    elif [ "$2" = "getroute" ]; then
        $PWD/$API_EXAMPLE_PATH/get_route $3 $4 
    elif [ "$2" = "report" ]; then
        $PWD/$API_EXAMPLE_PATH/report $3 $4 $5 $6 $7
    elif [ "$2" = "example" ]; then
        $PWD/$API_EXAMPLE_PATH/example $3 $4
    elif [ "$2" = "simulator" ]; then
        if [ $# -eq 4 ]; then
            $PWD/$API_EXAMPLE_PATH/simulator $3 $4 
        elif [ $# -eq 5 ]; then
            $PWD/$API_EXAMPLE_PATH/simulator $3 $4 $5
        elif [ $# -eq 6 ]; then
            $PWD/$API_EXAMPLE_PATH/simulator $3 $4 $5 $6
        else
            usage
        fi
    elif [ "$2" = "qps" ]; then
        $PWD/$API_EXAMPLE_PATH/qps $3
    fi
elif [ "$1" = "reporter" ]; then
    cd $REPORTER_PATH
    ./bin/reporter
elif [ "$1" = "dns" ]; then
    cd $DNS_PATH
    ./bin/dns
elif [ "$1" = "lbagent" ]; then
    cd $LBAGENT_PATH
    ./bin/lb_agent
elif [ "$1" = "help" ]; then
    usage
else
    usage
fi